function dy = rate_eq5(t,y,v)
f=20e+3;%repeat frequency
l0=5e-3;%Gain rod length (mm)
l=100e-3;%Resonator length (mm)
gama=1;%Reversal factor
tavf=35.7e-6;%Spontaneous lifetime
R=0.98;%Output mirror reflectance
landain=443e-9;%Pump wavelength
sigma=2.2e-23;%stimulated section
t1=4.15e-6;%high voltage Q-switch duration time
t2=17.4e-6;%low voltage Q-switch duration time
deltavh=500e+6;%The FWHM of spontaneous radiation
landaout=639e-9;%output wavelength 
L0=0.0001;%Loss per double pass of 1th mode
L1=0.0002;%Loss per double pass of 2th mode
L2=0.0003;%Loss per double pass of 3th mode
Rp=6.23e+28;%Pumping rate
n=2.047;%Refraction of Q-switched crystal
n0=1.45;%Refraction of laser crystal
lq=0.01e-2;%Q-switched crystal length
Ntot=31.4e+23;%Total inversion population
c=3e+8;%light speed
epsilon=8.85e-11;
pab=2.8;%wat
h=0.3e-1;%
mu=4.7665e-15;
gv0=2 ;%gain function of the th i longitudinal mode
sigman1=0.9;%
sigman2=0.5;%
lambdaP = 1530E-18;
v1=c/lambdaP;
v0=v1-9*deltavh;
T=0.5 ;%dissipative loss
% Length of active fiber (m)
lr =10;
tr = lr/c;
if t<t1
LQS=sigman1;
Li=L0;
else if t<t2
LQS=sigman2;
Li=L1;
else
LQS=0;
Li=L2;
end
end

sigmai=2*(pi^2)*abs(mu)^2*v*gv0*((1+(4*(v-v0)^2)/(deltavh^2))^(-1))/(3*n*epsilon*c*h);
dy = zeros(3,1);
dy(1)=Rp*((Ntot-y(1))/Ntot)-gama*c*sigmai*y(1)*y(2)-y(1)/tavf;
Lres=(-log(R)+LQS+T+Li);
tavi=+tr/Lres;
%sigmai=+2e-25;
dy(2)=gama*c*sigmai*y(1)*y(2)-y(2)/tavi;
t
end
//

clear all
clc
close all
deltavh=500e+6;
% Speed of light
c = 299792458;
lambdaP = 1530E-18;
v1=c/lambdaP;
v0=v1-9*deltavh
vv = v0:deltavh:v1;
for iii=1:length(vv)-7
ti = 0;
    tf = 35.65E-6;
    tspan=[ti tf]; 
   y0=[1e-6; 1e-6;1e-6]
%y0=[0; 0; 0]
%y(1) = Photon Density
%y(2) = Inverted Population Density
%y(3) = Photocarrier Density
% Frequency of signal (Hz)
v=vv(iii)
iii
[T,Y]= ode45(@(t,y) rate_eq5(t,y,v),tspan,y0);

figure(1);
    hold on
    plot(T,Y(:,1));
    title('Inverted Population Density '); 
xlabel('Time'); 
ylabel('Inverted Population Density')
     hold off
    figure(2);
    hold on
    plot(T,Y(:,2));
   title('Photon Density'); 
xlabel('Time'); 
ylabel('Photon Density'); 
 hold off
   % figure(3);
    %hold on
    %plot(T,Y(:,3));
  %title('Photocarrier Density'); 
%xlabel('Time'); 
%ylabel('Photocarrier Density'); 
% hold off
end
%figure(4)
%plot(T(500:800,1),Y((500:800),2))
